# These are supported funding model platforms

ko_fi: dede_klender # Replace with a single Ko-fi username
custom: https://paypal.me/dedeklender, https://teer.id/dede_klender # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
